### ISSUE TITLE
error in _has_return_call

### ISSUE THREAD

**Issue by shigeshige** [shigeshige/py-ut-generator#7]
```
Traceback (most recent call last):
  File "c:\users\user\.pyenv\pyenv-win\versions\3.8.2-amd64\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\.pyenv\pyenv-win\versions\3.8.2-amd64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\codes\anken\dell\insert-script\.venv\Scripts\pyutgen.exe\__main__.py", line 7, in <module>
  File "c:\codes\anken\dell\insert-script\.venv\lib\site-packages\pyutgenerator\run.py", line 61, in main
    parse_file(args.filename, args.ovewrite)
  File "c:\codes\anken\dell\insert-script\.venv\lib\site-packages\pyutgenerator\run.py", line 38, in parse_file
    fpo = ast_util.make_func_obj(t_func, pkg, mdn, module)
  File "c:\codes\anken\dell\insert-script\.venv\lib\site-packages\pyutgenerator\ast_util.py", line 232, in make_func_obj
    get_calls(t_func),
  File "c:\codes\anken\dell\insert-script\.venv\lib\site-packages\pyutgenerator\ast_util.py", line 115, in get_calls
    has_return = _has_return_call(stm, func)
  File "c:\codes\anken\dell\insert-script\.venv\lib\site-packages\pyutgenerator\ast_util.py", line 148, in _has_return_call
    for stm2 in ast.walk(stm.items):
  File "c:\users\user\.pyenv\pyenv-win\versions\3.8.2-amd64\lib\ast.py", line 332, in walk
    todo.extend(iter_child_nodes(node))
  File "c:\users\user\.pyenv\pyenv-win\versions\3.8.2-amd64\lib\ast.py", line 216, in iter_child_nodes
    for name, field in iter_fields(node):
  File "c:\users\user\.pyenv\pyenv-win\versions\3.8.2-amd64\lib\ast.py", line 204, in iter_fields
    for field in node._fields:
AttributeError: 'list' object has no attribute '_fields'
```

**Comment by shigeshige** [comment]
end
